# Generated by Django 3.1.4 on 2021-01-02 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('center_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ingrese el nombre del género', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(verbose_name=9)),
                ('CIF', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['center_id', 'CIF', 'name', 'address', 'phone_number', 'email'],
            },
        ),
    ]
