# Generated by Django 3.1.4 on 2021-01-02 23:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
