# Generated by Django 3.1.4 on 2021-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210103_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centers',
            options={},
        ),
        migrations.AlterField(
            model_name='centers',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='centers',
            name='phone_number',
            field=models.IntegerField(max_length=9),
        ),
    ]
