# Generated by Django 3.1.4 on 2021-01-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210104_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signing',
            name='end_rest',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='signing',
            name='end_work',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='signing',
            name='start_rest',
            field=models.TimeField(blank=True),
        ),
    ]
