# Generated by Django 3.2 on 2021-04-15 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('CIF', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.UUIDField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='user', verbose_name='User ID')),
        ),
        migrations.AlterField(
            model_name='user',
            name='center_id',
            field=models.UUIDField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='centers', verbose_name='Center ID')),
        ),
    ]
