# Generated by Django 3.2 on 2021-04-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0003_alter_user_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center_id',
            field=models.UUIDField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='centers', verbose_name='Center ID')),
        ),
    ]
