# Generated by Django 3.2 on 2021-04-15 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0005_auto_20210415_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Center'), (2, 'Admin')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
