# Generated by Django 3.2 on 2021-04-15 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0006_auto_20210415_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='center_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Center'), (2, 'Admin')]),
        ),
    ]
