# Generated by Django 3.2 on 2021-04-15 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0009_alter_user_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.UUIDField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='user')),
        ),
        migrations.AlterField(
            model_name='signing',
            name='signing_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='center_id',
            field=models.UUIDField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='centers')),
        ),
    ]
